#!/bin/sh

# Erstelle Ordner, wenn nicht bereits vorhanden
mkdir -p files
# Kopiere *.txt Dateien vom aktuellen Ordner in den Zielordner.
# Unterdrücke Fehlermeldung wenn keine *
cp -n *.txt files 2>/dev/null
cd files; ls -S -r >../myfiles

